hash-format = "sha256"

[[files]]
file = "config/BiblioCraft.cfg"
hash = "73d8cdef17b0de12c847971ed957a81b85f96971a8b30fb27f60b30f3bc27771"

[[files]]
file = "config/IGWMod.cfg"
hash = "52cd917ee9452639272289581db8c5cd4d299326b68bf80a04b1d13f5362d784"

[[files]]
file = "config/MrTJPCore.cfg"
hash = "b133701ea057c550fb94eab97bfc1784f9292ba07c02fb4e33c0d715816fec31"

[[files]]
file = "config/NEI/client.cfg"
hash = "1a034c70e1541ff64a4ccaf6941ce33e4fd5e85d1c89022b7ada2b29e2ec60c2"

[[files]]
file = "config/NGTLib.cfg"
hash = "870e4780c764caa65053a30dadf8cec420176c84c81ff4947fefebd8ee7b86e3"

[[files]]
file = "config/OpenComputers.cfg"
hash = "4af3b716d532bf7490e53b4ead18403af83162c2e0e3b957882d34f979e5cba6"

[[files]]
file = "config/PneumaticCraft.cfg"
hash = "1a0165aebeb6d8a40868ad9f48d4b2e503a4dd10863527b702f645c06c39e0d3"

[[files]]
file = "config/ProjectRed.cfg"
hash = "5030b198c5bee3798ef8c1e4fbcfa5d0b824c90f7b1a173be3e3f67cabe08695"

[[files]]
file = "config/RTM.cfg"
hash = "8d999e5bb932c4bda5a17a91f8da084d4acced38ac7750296242faa6cac68b28"

[[files]]
file = "config/Wintercraft.cfg"
hash = "22bc4fe894d5e64971dc408315cb54783296d712f3527820ee423db1fdb90b00"

[[files]]
file = "config/WirelessRedstone.cfg"
hash = "06b2566fdb667718c2cadfceca995e2c742c9c364005209893cee9e325e0d7af"

[[files]]
file = "config/archaicfix.cfg"
hash = "a25be2578730f8b702e73299603b4f478a5b7701167acbcd5f8ed923bf95e442"

[[files]]
file = "config/buildcraft/main.cfg"
hash = "802f3c2e57a0c700dd29f9c058469d78675c11d08f09c379b6057fd8af193427"

[[files]]
file = "config/cfm.cfg"
hash = "7e5b00d156365e729d7a6ff0018766186face86148798a816ef8b002ac59519e"

[[files]]
file = "config/cofh/core/common.cfg"
hash = "e6aaa1da5333d497de81df71eef3f071aa6115adeb251e212236ce9a20dc0622"

[[files]]
file = "config/forge.cfg"
hash = "a9c0601a9a064a307a6a008d33963539f51f292e42f4f0724c037fdc2d8c7bd0"

[[files]]
file = "config/hodgepodge.cfg"
hash = "898ea234a80d481901fb74a329173f6edbd87973df6ed5a4607a5a1a4f6705a7"

[[files]]
file = "config/malisisdoors.cfg"
hash = "c149c83873e8e91897c65a7e3d2d59ec6b59a29635a4ce60e642d43447e66311"

[[files]]
file = "config/railcraft/blocks.cfg"
hash = "ab0f99f774aebfe76a0967e2739cf2ce009236cf3454b017d6e808482b5fa0ca"

[[files]]
file = "config/railcraft/railcraft.cfg"
hash = "09c182482be0a8b330a0ab04b69e5b6e091edbcad220a2bd8caa2d468c01f0d9"

[[files]]
file = "config/shaders.properties"
hash = "7a8a3e8f95b26d7fd7f0b028160324b8e62b1fb370231adbc3ccaae412aa4592"

[[files]]
file = "config/smallboats.cfg"
hash = "e7b2f75b9327118c2c02819fb1a2d805a805f81d5fdce26e50f837df40c50c30"

[[files]]
file = "mods/1.7.10/baubles-expanded.pw.toml"
hash = "d0dedd0df65b46cd0660396c4b30285a04b13f41b813562aeeb95bb77b2a2d17"
metafile = true

[[files]]
file = "mods/1.7.10/forgemultipart.pw.toml"
hash = "bd18ea1b5dac3ebe81efa8dc2885c63642a8a6ff0b3d7cd03e1438b6fcaf65e9"
metafile = true

[[files]]
file = "mods/1.7.10/forgerelocation.pw.toml"
hash = "121b1fa1a31f533acd54741b1a5f0ed322fa3d10e1d72cd244c7f469ab8d4cf8"
metafile = true

[[files]]
file = "mods/1.7.10/forgerelocationfmp.pw.toml"
hash = "4d37484ef5e9cd37e2ef0660adac1e35834d2489739abbcdfec1e2ab4c0803b4"
metafile = true

[[files]]
file = "mods/1.7.10/mrtjpcore.pw.toml"
hash = "b11b1f19eba53aa783ebb7047a9d0a2b80e6857d7eb6c7ecc1d879d6e3830118"
metafile = true

[[files]]
file = "mods/StationsMod-1.7.10.5.jar"
hash = "14e699ee2191141bd41626cb96b61fef537e319b811eaeddcc8a9ff3c2f61d33"

[[files]]
file = "mods/angelica.pw.toml"
hash = "8b3a69fd62cdf23f4b397f576b894688ee4779df43bb4a0a5545d0716098eb23"
metafile = true

[[files]]
file = "mods/archaicfix.pw.toml"
hash = "52167fe78f9cc08a6bc6fb5005db660b02ffb89e16bc8331510416fe23416050"
metafile = true

[[files]]
file = "mods/bibliocraft.pw.toml"
hash = "348cdb59de511d7b3385418ceeaaf0332075d4e5edd9fd8f354f205c284bde3e"
metafile = true

[[files]]
file = "mods/buildcraft.pw.toml"
hash = "10a335e51075d6666633ca08e8141076d4db8288a5995b40014c6df9ee2d4a41"
metafile = true

[[files]]
file = "mods/carpentersblocks.pw.toml"
hash = "80296f4737a6acc97e444ba8549ebe51f6060f29ec0e76def52617f421055788"
metafile = true

[[files]]
file = "mods/chisel.pw.toml"
hash = "e05e261e4b7eae159f1deff4b9b436bcdfab8ee9f875d6dcf7f44764c136ea09"
metafile = true

[[files]]
file = "mods/codechickencore-unofficial.pw.toml"
hash = "cce16701c186c342f4ce0b20a41cafc4ae7af1a00e0bf85b6a26d89ee1ba99e7"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "532832dfebefa96635d1567dbfa473795f63dd86af44e770f3a2f34d8c858193"
metafile = true

[[files]]
file = "mods/cofh-lib.pw.toml"
hash = "1129db358c22dfe9c80c8251c6105e65dc633fe267788707424f7a593cc98bd7"
metafile = true

[[files]]
file = "mods/decocraft.pw.toml"
hash = "4dca4451404d68b3c14d919badd75b5a2264f9917b8a359f3e80ef06d13f2b4f"
metafile = true

[[files]]
file = "mods/dn01-variotram.pw.toml"
hash = "2c5a52ba6dd6e123535e067d0251b8075be43350777cad0e08cc1e3b1061a2c6"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "75c35f862264cb9d152265a19f13d25050adca2d61a426afa05febffe0bafd45"
metafile = true

[[files]]
file = "mods/foamfix-optimization-mod.pw.toml"
hash = "9c562e68ea529e4f835b9af28eda92fd88e65d7174d24c13bcbce162c49e9fd8"
metafile = true

[[files]]
file = "mods/fullscreen-windowed-borderless-for-minecraft.pw.toml"
hash = "2e61fd567c10e346687f6a2a337723bf5d17fb4059fdb82ec50ab6dc7508ab05"
metafile = true

[[files]]
file = "mods/furenikusroads.pw.toml"
hash = "d2069490371147c83355a30b0d7d4d7a438ea76476c52e7510e135cf056fe0b6"
metafile = true

[[files]]
file = "mods/gtnhlib.pw.toml"
hash = "b01e5648aad46c0bd8c71691bbcff3a6d973bbdae0d72e4f1738b11af5623e45"
metafile = true

[[files]]
file = "mods/hi03bumpingpostpack1.0.pw.toml"
hash = "7571e91b5e95435dfafbffc133cf319fd645066812b2a499cdf0ef0cbbf104db"
metafile = true

[[files]]
file = "mods/hi03catenarypack_common_v02.pw.toml"
hash = "6df53f4ce00c11bd429bbe6e6959d64ff02c0e25a0add8e1ba28a6240b2c364d"
metafile = true

[[files]]
file = "mods/hi03expressrailway_catenary.pw.toml"
hash = "df9aea4405609144d6462d9e24ab53f2ea56611154b8781b340ae6d636ee2edb"
metafile = true

[[files]]
file = "mods/hi03expressrailway_catenary_w51.pw.toml"
hash = "cfe82578d139c2334262a82908d49af4428641a23930e0b6fcf1cfce16d04745"
metafile = true

[[files]]
file = "mods/hi03expressrailway_railassets.pw.toml"
hash = "46b8a9a5f44f7970c756b3230739fef91617150644b6e9693101da59105d13a5"
metafile = true

[[files]]
file = "mods/hi03expressrailway_rails1067mm.pw.toml"
hash = "466ede44d4fd3929716f7156e6c27db7e8c56faca386acded67b7212534d7bf7"
metafile = true

[[files]]
file = "mods/hi03railstructure.pw.toml"
hash = "8dee2d0e0e451bf0dc12f15e080dad1e05db99fa0da31a85ea90614ab5d4d355"
metafile = true

[[files]]
file = "mods/hi03soundlib.pw.toml"
hash = "672bca495dbf219bab3519717c4d22e37be4cb6dfb1e4cfededcd83833349f36"
metafile = true

[[files]]
file = "mods/hi03structurepack1.0.2.pw.toml"
hash = "7e2da566bdfad57a7fee712df0cb601d211e60f10ad211a8049a4c668759ab93"
metafile = true

[[files]]
file = "mods/hi03trainpack1.14.1_1.7.10.pw.toml"
hash = "61472072755ef3dcf10a63496532ff7789b2c040293db9aa113e662e5347a4e8"
metafile = true

[[files]]
file = "mods/hodgepodge.pw.toml"
hash = "b049771c32a81fa53568e77a0476e457099573a6e27958d9b5301058080a9b02"
metafile = true

[[files]]
file = "mods/ic2-classic.pw.toml"
hash = "dff298cb8562e5395a31bd09b1f9e48c2040c8e294975348bf304afeb3389eae"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "2f92bb1aea927bab8e4b18840c5498a971c21e211d9e74a51304c3377a311110"
metafile = true

[[files]]
file = "mods/kaizpatchx.pw.toml"
hash = "10c867e7f91b33818b983beff93c4e994a97450ce6f118a61b96316063f62b3c"
metafile = true

[[files]]
file = "mods/kt-nagarapack_rtm_ver0.5.pw.toml"
hash = "54ebc4fae1a78972db8af2fd5fea9fa5cf8478acb8984f51e57e3acab7701576"
metafile = true

[[files]]
file = "mods/malisisdoors.pw.toml"
hash = "2bd36e7387858b48488ce02dd9ec9addee045f44467e8fbd069c1ffe4bdb08d6"
metafile = true

[[files]]
file = "mods/moarsigns.pw.toml"
hash = "6b5ea216cfb3290fafe52ee12bba129207320853605ac0db89e29c71f0c453a5"
metafile = true

[[files]]
file = "mods/modelpack_nsw_nif_240207.pw.toml"
hash = "4d1dd7b65e29c26dddd09e437e17825bb43a95596922f0a29ab07f9f8ea60ce4"
metafile = true

[[files]]
file = "mods/modelpack_pc28ksoundlib_revision.pw.toml"
hash = "d750279ca4dc9fd16f03b1f28078cd1937a21f6f40a5c317f5498772492aea04"
metafile = true

[[files]]
file = "mods/modelpack_srteuropean_241030.pw.toml"
hash = "ddea8778688031fe11f13ffb4d08d0706dfdaacfb043071f138349c720144989"
metafile = true

[[files]]
file = "mods/monoblocks.pw.toml"
hash = "29044804d1822f583f129724142c2db5e75ed26ae3d853284e717410b2e3e10b"
metafile = true

[[files]]
file = "mods/mp1_9_4-fix.pw.toml"
hash = "4e37fdce97704b36af21d1618772baac2a62a3b1abd6effddb0ba309ff837c7c"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
hash = "2bf65d3d2f8d6d1e09145e3c6b08a56769f7975a667581fdcd28e72ffb7b65e9"
metafile = true

[[files]]
file = "mods/n026-hiroshimatram.pw.toml"
hash = "279c346c40142b4438d1ac185c5c58fe68322d077fc733108ef8cd65285ad3b5"
metafile = true

[[files]]
file = "mods/na04-nb-assets.pw.toml"
hash = "dde81f2284f9d72d797e3a551ec04c609f6651ff8c8c550f28e0a920cf777659"
metafile = true

[[files]]
file = "mods/notenoughitems-gtnh.pw.toml"
hash = "4f444c9190d4c497cd91dcc2b6559c85eb7e8a91c1cd5a8d2480e8570baedcec"
metafile = true

[[files]]
file = "mods/nr01-nb-rails.pw.toml"
hash = "6e2818633a1fb061214a3586b8bf0effb43bc69fb564f9e84ff1d9b50b525d8d"
metafile = true

[[files]]
file = "mods/opencomputers.pw.toml"
hash = "71be6fe1df27cc599b78b472ca9d95e49d160ce0925c27f6f215e23b8ded14a2"
metafile = true

[[files]]
file = "mods/pams-harvestcraft.pw.toml"
hash = "5cd824f1d1a4bfd2a90504eeed416bdb68fd55bbcd93e137ff1c651794d95943"
metafile = true

[[files]]
file = "mods/planetguylib.pw.toml"
hash = "d9d1d852324f317c3acce732444c8164d5e3106dffda3ddeb86ce15b2374c302"
metafile = true

[[files]]
file = "mods/pneumaticcraft.pw.toml"
hash = "7754fedf1187797bbbb60c01d845d2910cd630eee7cb5e2ee6995e737caefcb5"
metafile = true

[[files]]
file = "mods/projectred.pw.toml"
hash = "df3ac36c834b80a0063c17f80776561c258fbb3d6187aeb6f5ca37421f811c63"
metafile = true

[[files]]
file = "mods/railcraft-cosmetic-additions.pw.toml"
hash = "aa7d7579248bd2bbe3cf5b24c448d300c84f59408798eef82420482eda9db04c"
metafile = true

[[files]]
file = "mods/railcraft.pw.toml"
hash = "d9ce32f79db6367a640da4187152c106e09433aca8ba31c6f612a6c257d86a8b"
metafile = true

[[files]]
file = "mods/remain-in-motion.pw.toml"
hash = "62374193eedcf6fedc98c61ef53778954d420ef17a8d61f1886dc54f2fe32576"
metafile = true

[[files]]
file = "mods/road-stuff.pw.toml"
hash = "f0f8993ab52f710aa5d76366b38a0f3f45d81dfd6b8cd8625aa031c87b192717"
metafile = true

[[files]]
file = "mods/rtm-monorail-bubblecar.pw.toml"
hash = "45740bfd6b12780b3f7e7b937089714f9864423f97f575ba1733eb4c93e1cb01"
metafile = true

[[files]]
file = "mods/rtm-rail-v2.0.pw.toml"
hash = "a77b92ea1378f3d3169938893beab3d8b7598531c27ebfd2d81ed3d7085db95c"
metafile = true

[[files]]
file = "mods/rtm-scriptssoundlib-v2.9.3.pw.toml"
hash = "1619e2ab3d52e5bb3097a2188443a87e013bee7a6a862d05045b0d7fee318101"
metafile = true

[[files]]
file = "mods/rtm-taiwan_mrt-kaohsiung-v3.3.pw.toml"
hash = "0425e1f9cdd3b40b78949762ddc500446632f770c1e2214ba76e5506c92fdeef"
metafile = true

[[files]]
file = "mods/rtm-taiwan_tra-v1.0.pw.toml"
hash = "c20f93f2c56a0ce06974417a92a34be80974940042205ae90661eca6e9bf1e87"
metafile = true

[[files]]
file = "mods/rtm-u.k_london_underground-v3.0.pw.toml"
hash = "4cd614da21bc6650369df562f0bbbcde0d8b235dd6ab82678b4dda7001ad408a"
metafile = true

[[files]]
file = "mods/rtm_hk_trampack.pw.toml"
hash = "c576e43d6d8cf7e79310d501132b59747b1c68d7e5cd266a3925a990ca8c1c52"
metafile = true

[[files]]
file = "mods/rtm_keihan600.pw.toml"
hash = "e54f3bdbb7684d163f76d157c945bdfd1c18dc14a9292e000a6807987a2df0c8"
metafile = true

[[files]]
file = "mods/rtm_lmcommuter_kit.pw.toml"
hash = "18978233daee9bd9efefc0bc7f1424ef383dfaaf6d9ee66607d98e86ce8e36b0"
metafile = true

[[files]]
file = "mods/rtm_tkmnp_1.2.pw.toml"
hash = "1d0d8c12c47684503f1c8500e977cf47d29be5ffe59378b53a8fef5113850373"
metafile = true

[[files]]
file = "mods/rtm_tkmtp_13.4.pw.toml"
hash = "25399017e69bd3436465972700af590f84349ea6936c8a52ce0631bc68c7f819"
metafile = true

[[files]]
file = "mods/rtm_ttkrp_6.0.pw.toml"
hash = "e9594917ef40556784740791ceb12ed4c2d3d382b4c3914ca6f2ecac046d14ff"
metafile = true

[[files]]
file = "mods/serializationisbad.pw.toml"
hash = "ecc928d5a6f9fd0d4a3b015e174bf54da4db56dc143512cb93d96954113b1547"
metafile = true

[[files]]
file = "mods/small-boats-mod.pw.toml"
hash = "e18eee1935fb1851e78ca5da7a93f9aac4b1554b266466bc513fe0b9fc88d432"
metafile = true

[[files]]
file = "mods/spiritedawaytrain.pw.toml"
hash = "30998d335a6c2d57b55beef571e09f19040d2efcc819606f1ecfe3d77ed1de3a"
metafile = true

[[files]]
file = "mods/style.pw.toml"
hash = "b9c4089da22149f8698327ee361f33c21ed5cc523b7ce2a6494b7a298631f52a"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "df50657f40e3b77b110e019f6f2b1d010468ac5f0a26f807bae7258e9951d06b"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "52c5a415a7bc071332ef8c791d4b97910cfba93c527c9f8aabfc05af63d30321"
metafile = true

[[files]]
file = "mods/traincraft.pw.toml"
hash = "ee0acbcc7380ec5aad1765f38c6f6911368dfc0ca4840179e8cfe6ec993a23d9"
metafile = true

[[files]]
file = "mods/trainpack_jre_see4_v1.1.pw.toml"
hash = "7b9f4fa3454cd61a1aba6e2d34622baa4fea3ab2d24a2d0cbd5abac08ce68e4f"
metafile = true

[[files]]
file = "mods/trampack_v_b1.2.1-universal.pw.toml"
hash = "7ec74deda386a58a62d6516b85601b2ca8ddef34c456d944daebbaf1c0e3b0b6"
metafile = true

[[files]]
file = "mods/tx-1000.pw.toml"
hash = "59122348e98568541854e5df50cedb296a4dd0990b3ca433fdfcebcae06f9341"
metafile = true

[[files]]
file = "mods/unimixins.pw.toml"
hash = "9b84a015e887f80d3443d09298620587c8cf743a9dda35df98e10e538af7a2fe"
metafile = true

[[files]]
file = "mods/wintercraft-gruntpie224.pw.toml"
hash = "b397e3f79c58cccd5fdd0265dce948abbfb054f6405cbf735a5fc88cea966ed4"
metafile = true

[[files]]
file = "mods/wirelessredstone-cbe.pw.toml"
hash = "d1c8096dcb62d6bb0e7f01a5efa2fd4ec08bb77b0d05d508d8255dc6886290a0"
metafile = true

[[files]]
file = "mods/worldedit-gtnh.pw.toml"
hash = "f60bd543ac70cd589851543099d39cfa53b7e329ac32c9b4660d42e80352ab00"
metafile = true
