name = "Efrana"
author = "Elanor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4f7daa203864a768ebb0cf798f6fee0bb7f142d1a384ef9281b5a7b92f7000d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
