name = "Efrana"
author = "Elanor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef6a29bdfe781185c3d9e32ddb7b8b3f1c96a1b084e62bdacd55c9fa44cb115d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
